# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mVCzEmXou89sVfzVyr3w01hPpWWltr9m
"""

import tensorflow as tf
import sklearn.datasets
import streamlit as st
st.title("Iris Classifier- API")

sl = st.slider('Sepal Length', 4.3, 7.9, 0.5)
sw = st.slider('Sepal Width', 2.0, 4.4, 0.5)
pl = st.slider('Petal Length', 1.0, 6.9, 0.5)
pw = st.slider('Petal Width', 0.1,2.5, 0.5)

from sklearn.datasets import load_iris

iris = load_iris()

iris.data

iris.target

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3)

model = kmeans.fit(iris.data)

model.labels_

model.cluster_centers_

sepallength = float(input("Please enter the Sepal Length: "))
sepalwidth = float(input("Please enter the Sepal Width: "))
petallength = float(input("Please enter the Petal Length: "))
petalwidth = float(input("Please enter the Petal Width: "))

result = model.predict([[sepallength,sepalwidth,petallength,petalwidth]])
if result == 0:
  print('Iris setosa')
elif result == 1:
  print('Iris virginica')
else:
  print('Iris versicolor')

